In [ ]:
# generate reflectance cubes with SVM Classifier.

In [1]:
%matplotlib qt

In [2]:
cube_sample1 = r'C:\Users\baolab\Desktop\ashish\root1\hyper_seeds\data\numpy_files\51_000_0008.npy'
cube_sample1

'C:\\Users\\baolab\\Desktop\\ashish\\root1\\hyper_seeds\\data\\numpy_files\\51_000_0008.npy'

In [3]:
import numpy as np
reflectanceX = np.load(cube_sample1)

print(reflectanceX.shape)
print(reflectanceX)

(410, 410, 164)
[[[0.1111 0.     0.1428 ... 0.4224 0.4224 0.4224]
  [0.0714 0.0909 0.25   ... 0.4398 0.4398 0.4398]
  [0.     0.     0.1666 ... 0.4153 0.4153 0.4153]
  ...
  [0.     0.1428 0.2    ... 0.4265 0.4265 0.4265]
  [0.2857 0.3333 0.25   ... 0.3771 0.3771 0.3771]
  [0.1111 0.125  0.1428 ... 0.3864 0.3864 0.3864]]

 [[0.1111 0.1111 0.1111 ... 0.4179 0.4179 0.4179]
  [0.2222 0.1111 0.1    ... 0.4197 0.4197 0.4197]
  [0.1818 0.1818 0.3    ... 0.4015 0.4015 0.4015]
  ...
  [0.1428 0.     0.     ... 0.4377 0.4377 0.4377]
  [0.2    0.     0.     ... 0.405  0.405  0.405 ]
  [0.1428 0.1428 0.125  ... 0.4163 0.4163 0.4163]]

 [[0.1111 0.2222 0.3    ... 0.4196 0.4196 0.4196]
  [0.25   0.1666 0.1111 ... 0.4007 0.4007 0.4007]
  [0.25   0.25   0.25   ... 0.409  0.409  0.409 ]
  ...
  [0.6    0.3333 0.1428 ... 0.4346 0.4346 0.4346]
  [0.2222 0.2222 0.1    ... 0.4253 0.4253 0.4253]
  [0.3    0.3    0.2    ... 0.429  0.429  0.429 ]]

 ...

 [[0.5833 0.5833 0.4    ... 0.439  0.439  0.439 ]
  [0

In [4]:
my_hypercube = reflectanceX

### Extract data and train SVM classfier

In [9]:
import importlib
import utils.utils

importlib.reload(utils.utils)
from utils.utils import run


In [10]:
X, y = run(reflectanceX)

Captured 4 snack pixels and 2 background pixels.
Final feature matrix shape for SVM: (6, 164)


In [12]:
X.shape

(6, 164)

In [13]:
y


array([1., 1., 1., 1., 0., 0.])